### PR TITLE
Add ro.sf.lcd_density

### PR DESCRIPTION
**Pull request by jhenrique09**
Fix RR build

### CODE REVIEW

**Comment by skritchz** [comment]
The ro.sf.lcd_density depends on the variant it is set by the init

https://github.com/boulzordev/android_device_lenovo_A6020/blob/cm-14.1/init/init_A6020.cpp#L73

**Comment by jhenrique09** [comment]
How to fix this error? 

04:41:39 loaded device-specific extensions from /tmp/targetfiles-1M9mpr/META/releasetools.py
04:41:39 using prebuilt recovery.img from IMAGES...
04:41:39 
04:41:39    ERROR: couldn't find ro.sf.lcd_density in build.prop
04:41:39 
04:41:39 ninja: build stopped: subcommand failed.
04:41:39 make: *** [ninja_wrapper] Error 1


https://github.com/ResurrectionRemix/android_build/blob/nougat/tools/releasetools/ota_from_target_files.py#L702

I use jenkins

**Comment by skritchz** [comment]
You should make a pull request to the RR.
Or maybe there is a way to patch the info_dict on the fly.

**Comment by skritchz** [comment]
This isn't very important for RR, it is only needed for display purpose.

**Pull request closed without merging**
