### PR TITLE
liblights: Fix green/red color (it was revert)

### PR DESCRIPTION
**Pull request by Vgdn1942**

### CODE REVIEW

**Comment by skritchz** [comment]
What is the behavior on the stock rom. I don't remember.
Notification => Blinking Green?
Charger => Red?

What does it do when device is charging and we get a notification.

**Comment by Vgdn1942** [comment]
Yes, Notification => Blinking Green, Charger => Red.
And when you select the settings in red lights, work green light (I use "config_multiColorNotificationLed" & "config_multiColorBatteryLed" in https://github.com/CyanogenMod/android_frameworks_base/blob/cm-13.0/core/res/res/values/config.xml for test).

Priority is set in the file:
https://github.com/CyanogenMod/android_frameworks_base/blob/cm-13.0/services/core/java/com/android/server/lights/LightsManager.java
If

**Comment by skritchz** [comment]
Ok, thanks for pointing that out, I was trying to figure out the values by debugging the dump. I think it should be rewritten again. Because today it won't work depending on the current battery level.

**Comment by subha785** [comment]
Release a cm14 build with current fixes.

**Pull request closed without merging**
