### PR TITLE
A6020: Drop boringssl-compat and stlport dependencies

### PR DESCRIPTION
**Pull request by karthick111**
Signed-off-by: karthick111 <karthickrko61@gmail.com>

### CODE REVIEW

**Comment by skritchz** [comment]
I tested this on lineage14.1 but it seems like libmmqjpeg_codec still need boringssl compat.

**Comment by karthick111** [comment]
I will do something for it

**Comment by karthick111** [comment]
Did u try a build without boringssl-compat and stlport ?

**Comment by skritchz** [comment]
Yes I removed the shim for mmjpeg and it worked. Didn't test removing the
libs tought

**Comment by karthick111** [comment]
Previously there is any frame drop or lags in ui ?
With old adreno blobs ?

**Comment by skritchz** [comment]
I don't use it as a daily phone so I don't notice this kind of things

**Comment by Shr3ps** [comment]
So what about this PR ?

**Comment by karthick111** [comment]
Let's hold it for few days 
Needs test

**Pull request closed without merging**
