### PR TITLE
VoLTE Support (Kanged Though ;_;)

### PR DESCRIPTION
**Pull request by Ayush-Walia**
IMS Commits for device tree, it won't work until vendor is also updated...

### CODE REVIEW

**Comment by skritchz** [comment]
Don't you need a libshims_ims in order to fix the error?
"/system/bin/imscmservice": cannot locate symbol "ENGINE_cleanup" referenced by "/system/vendor/lib64/lib-imsdpl.so"

Or did you find some other binaries that do work without it

**Comment by skritchz** [comment]
Seems like ims_rtp_daemon and imscmservice are not needed for IMS to work correctly

**Comment by karthick111** [comment]
i will look into ims stuffs

**Comment by skritchz** [comment]
This would be great, I don't have anything to test it on. I did a build but I'm doing it blindly

**Comment by Ayush-Walia** [comment]
ims_rtp_daemon is something related to video calls through dialer, delete it and video calls won't work..
Anyway no one uses that , so deleting that won't really matter...

**Comment by chaubeyprateek** [comment]
Code-freak you are not the real author of this -_-
Why copying my work -_-

**Comment by Ayush-Walia** [comment]
Lol, its open -_- 
https://github.com/CyanogenMod/android_device_motorola_msm8916-common/commit/30d09036446e98c0f640d42c89fa2a3c746308c7

**Comment by Shr3ps** [comment]
Which means we will not merge this PR, but cherry the original commit instead to preserve authorship :)

**Comment by skritchz** [comment]
Yeah I actually also did the same thing yesterday, except the overlay part

**Comment by skritchz** [comment]
But anyway thanks for helping on this. ANd let's hope we'll make a fully working ROM for all phone version.

**Comment by chaubeyprateek** [comment]
OK its open 
Carry  on your work :D

**Comment by rahulsnair** [comment]
@C0de-freak being open doesn't give you the authority to kang it. You need to keep the authorship.. thats what opensource is all about.

**Comment by Ayush-Walia** [comment]
Sorry, its my fault that i didn't cherry-picked it, secondly this might help with vendor part..
https://github.com/FireLord1/android_vendor_motorola/commit/8defe4abd98d2273c82d2679c3f52dedfb58f524

**Comment by skritchz** [comment]
Actually we need some 64bits libraries too, so the proprietary file isn't correct

**Comment by Ayush-Walia** [comment]
I guess you are referring to these..
https://drive.google.com/file/d/0B3onz75ilXhzMktFMVF5bkxSdnM/view
These are extracted from stock rom(volte supported)..

**Comment by skritchz** [comment]
yes we'll need them. I have a vendor udpated with ims libs. I'm making  anew build with the enabled volte by default and we'll see.

**Pull request closed without merging**
