### PR TITLE
random stuff

### PR DESCRIPTION
**Pull request by Dinokin**
*According to qcom, this device gpu supports opengles 3.1 and vulkan.
*Removed redundant stuff from system.prop.
*This device is xxhdpi
*Corrected the size of the system partition (which means we can now flash gapps super if we want kek)

PS. I tested all these changes on my device

### CODE REVIEW

**Comment by Shr3ps** [comment]
What's your device variant?
I think some of your changes will not work on a40/a41

**Comment by Dinokin** [comment]
mine is a l36.
which changes wouldn't work?

**Comment by Shr3ps** [comment]
I was thinking about some props you edited, like heap vars
Like I told to scritch, I think we should have custom props for this per variant.

**Comment by skritchz** [comment]
yes the a40 uses some default values for most of the hwui fields. Forcing them might not be a good idea.

I'll make the required changes, in the init_a6020.cpp but I'll take this https://github.com/boulzordev/android_device_lenovo_A6020/pull/7/commits/4cd22cf1cecbbbd0670d77693a0f94de2fe5a940 commit anyway. I'll drop the other commit, the size are indeed incorrect, I was wrong with the factor 512 it's 1024. I'm fixing all the partitions sizes, but the value you wrote is still incorrect of a few bites

**Comment by Dinokin** [comment]
i suspected it was wrong kek i just copied the value that twrp reported and converted it to bytes

btw at least keep the gles and vulkan stuff cuz they are correct

**Pull request closed without merging**
